---
title: Mermaid Wardley Example
---
wardley
  title Platform Map
  anchor User [0.95, 0.65]
  component Portal [0.75, 0.62]
  component Runtime [0.55, 0.50]
  component Cloud [0.25, 0.40]
  User->Portal
  Portal->Runtime
  Runtime->Cloud
